
//login

export const EMPLOYEE_ID_DATA = 'id'
export const REGION_DATA = 'region'
export const SALES_OFFICE_DATA = 'masterSalesOfficeIds'
export const DESIGNATION_DATA = 'designation'
export const VIEW_CUSTOMER_DATA = 'isViewCustomers'
export const USER_ID_DATA = 'userId'
export const EMAIL_DATA = 'email'
export const COPS_NEXT_USER1_DATA= 'cops_next_user1'
export const COPS_NEXT_USER3_DATA = 'cops_next_user3'
export const COPS_CAPACTITY_DATA = 'cops_capacity'
export const PRIORITY_OTHER_BRAND_DATA = 'priority_other_brand'
export const MAXLOAD_OWN_BRANCH_DATA = 'maxLoadOwnBranch'
export const EMP_NAME_DATA = 'name'
export const BRANCH_DATA = 'branch'
export const DEPARTMENT_DATA = 'masterDepartmentId'
export const ACTUAL_DESIGNATION_DATA = 'actualDesignation'
export const VIEW_QUATOTAION_DATA = 'isViewQuotation'
export const MOBILE_DATA = 'mobile'
export const NEXT_USER_DATA = 'nextUserId'
export const COPS_NEXT_USER2_DATA = 'cops_next_user2'
export const MAXLOAD_PER_DAY_DATA = 'maxLoadPerDay'
export const MAXLOAD_OTHER_BRANCH_DATA = 'maxLoadOtherBranch'
